// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
///
///
///

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBlgLxCUuyLVbFTYoXjWREHQuZY7PPjGng',
    appId: '1:262229019426:web:4cb37bb2c10940f9b1737b',
    messagingSenderId: '262229019426',
    projectId: 'shyft-backoffice',
    authDomain: 'shyft-backoffice.firebaseapp.com',
    databaseURL: 'https://shyft-backoffice.firebaseio.com',
    storageBucket: 'shyft-backoffice.appspot.com',
    measurementId: 'G-FV9R1VSFEP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAKe_8vo6qVOvTroJOywh6l9Y9gufvG4uE',
    appId: '1:678186578279:android:92ec632ab43f919a05ffc2',
    messagingSenderId: '678186578279',
    projectId: 'shyft-auto-uat',
    databaseURL: 'https://shyft-auto-uat.firebaseio.com',
    storageBucket: 'shyft-auto-uat.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB6cg1GP9xXpSS5WGSaQuJvfEbANUXRXZs',
    appId: '1:678186578279:ios:b6b49f163c3aa63105ffc2',
    messagingSenderId: '678186578279',
    projectId: 'shyft-auto-uat',
    databaseURL: 'https://shyft-auto-uat.firebaseio.com',
    storageBucket: 'shyft-auto-uat.appspot.com',
    iosClientId:
        '678186578279-3qk3u91pt7nq46icaouocf7d7qa2hkgu.apps.googleusercontent.com',
    iosBundleId: 'com.futuredms.shyftDev',
  );
}
